/** Human-readable labels for enum values, shared by the web UI and exports. */
export const LABELS = {
  assetStatus: {
    PURCHASED: 'Purchased',
    REGISTERED: 'Registered',
    IN_STOCK: 'In stock',
    ASSIGNED: 'Assigned',
    IN_REPAIR: 'In repair',
    AVAILABLE: 'Available',
    LOST: 'Lost',
    RETIRED: 'Retired',
    DISPOSED: 'Disposed',
  },
  assetCategory: {
    LAPTOP: 'Laptop',
    DESKTOP: 'Desktop',
    MONITOR: 'Monitor',
    MOBILE: 'Mobile',
    TABLET: 'Tablet',
    PRINTER: 'Printer',
    SERVER: 'Server',
    NETWORK_EQUIPMENT: 'Network equipment',
    PROJECTOR: 'Projector',
    ACCESSORY: 'Accessory',
  },
  assetCondition: { NEW: 'New', GOOD: 'Good', FAIR: 'Fair', POOR: 'Poor', DAMAGED: 'Damaged' },
  assignmentStatus: { ACTIVE: 'Active', RETURNED: 'Returned', TRANSFERRED: 'Transferred' },
  historyAction: {
    CREATED: 'Created',
    UPDATED: 'Updated',
    STATUS_CHANGED: 'Status changed',
    LOCATION_CHANGED: 'Location changed',
    ASSIGNED: 'Assigned',
    RETURNED: 'Returned',
    TRANSFERRED: 'Transferred',
    MAINTENANCE_STARTED: 'Maintenance started',
    MAINTENANCE_COMPLETED: 'Maintenance completed',
    WARRANTY_UPDATED: 'Warranty updated',
    QR_REGENERATED: 'QR regenerated',
    DOCUMENT_ADDED: 'Document added',
    SOFTWARE_ASSIGNED: 'Software assigned',
    SOFTWARE_UNASSIGNED: 'Software unassigned',
    AUDITED: 'Audited',
    REPORTED_LOST: 'Reported lost',
    RETIRED: 'Retired',
    DISPOSED: 'Disposed',
  },
  employeeStatus: { ACTIVE: 'Active', ON_LEAVE: 'On leave', TERMINATED: 'Terminated' },
  locationType: {
    SITE: 'Site',
    BUILDING: 'Building',
    FLOOR: 'Floor',
    ROOM: 'Room',
    WAREHOUSE: 'Warehouse',
    DATA_CENTER: 'Data center',
    REMOTE: 'Remote',
    OTHER: 'Other',
  },
  vendorType: {
    SUPPLIER: 'Supplier',
    MANUFACTURER: 'Manufacturer',
    SERVICE_PROVIDER: 'Service provider',
    WARRANTY_PROVIDER: 'Warranty provider',
    SOFTWARE_PUBLISHER: 'Software publisher',
  },
  accessoryCategory: {
    CHARGER: 'Charger',
    MOUSE: 'Mouse',
    KEYBOARD: 'Keyboard',
    BAG: 'Bag',
    DOCKING_STATION: 'Docking station',
    HEADSET: 'Headset',
    CABLE: 'Cable',
    ADAPTER: 'Adapter',
    OTHER: 'Other',
  },
  maintenanceType: {
    REPAIR: 'Repair',
    PREVENTIVE: 'Preventive',
    UPGRADE: 'Upgrade',
    INSPECTION: 'Inspection',
  },
  maintenanceStatus: {
    SCHEDULED: 'Scheduled',
    IN_PROGRESS: 'In progress',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
  },
  priority: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High', CRITICAL: 'Critical' },
  licenseType: {
    PERPETUAL: 'Perpetual',
    SUBSCRIPTION: 'Subscription',
    VOLUME: 'Volume',
    OEM: 'OEM',
    OPEN_SOURCE: 'Open source',
    TRIAL: 'Trial',
  },
  ticketCategory: {
    HARDWARE: 'Hardware',
    SOFTWARE: 'Software',
    NETWORK: 'Network',
    ACCESS: 'Access',
    ASSET_REQUEST: 'Asset request',
    LOSS_REPORT: 'Loss report',
    OTHER: 'Other',
  },
  ticketStatus: {
    OPEN: 'Open',
    IN_PROGRESS: 'In progress',
    ON_HOLD: 'On hold',
    RESOLVED: 'Resolved',
    CLOSED: 'Closed',
  },
  documentType: {
    INVOICE: 'Invoice',
    WARRANTY: 'Warranty',
    HANDOVER_FORM: 'Handover form',
    RETURN_FORM: 'Return form',
    SIGNATURE: 'Signature',
    REPAIR_RECEIPT: 'Repair receipt',
    DISPOSAL_CERTIFICATE: 'Disposal certificate',
    PHOTO: 'Photo',
    LICENSE_CERTIFICATE: 'License certificate',
    AUDIT_REPORT: 'Audit report',
    OTHER: 'Other',
  },
  auditStatus: {
    DRAFT: 'Draft',
    IN_PROGRESS: 'In progress',
    IN_REVIEW: 'In review',
    CLOSED: 'Closed',
    CANCELLED: 'Cancelled',
  },
  auditResult: {
    PENDING: 'Pending',
    FOUND: 'Found',
    MISSING: 'Missing',
    UNEXPECTED: 'Unexpected',
    WRONG_LOCATION: 'Wrong location',
    DAMAGED: 'Damaged',
  },
  userStatus: { ACTIVE: 'Active', DISABLED: 'Disabled', LOCKED: 'Locked' },
  notificationType: {
    WARRANTY_EXPIRING: 'Warranty expiring',
    LICENSE_EXPIRING: 'License expiring',
    OVERDUE_RETURN: 'Overdue return',
    MAINTENANCE_DUE: 'Maintenance due',
    MAINTENANCE_UPDATE: 'Maintenance update',
    TICKET_UPDATE: 'Ticket update',
    AUDIT_ASSIGNED: 'Audit assigned',
    ASSIGNMENT_ACKNOWLEDGEMENT: 'Acknowledgement required',
    SYSTEM: 'System',
  },
} as const;

export type LabelGroup = keyof typeof LABELS;

export function label(group: LabelGroup, value: string | null | undefined): string {
  if (!value) return '—';
  return (LABELS[group] as Record<string, string>)[value] ?? value;
}
